### ISSUE TITLE
Get Error message: Karibu-Testing 1.2.x doesn't support Vaadin 14 Compatibility mode; please use Karibu-Testing 1.1.x instead

### ISSUE THREAD

**Issue by sashagorelikoriginal** [vaadin/tshirt-shop-example#2]
java.lang.IllegalStateException: Polymer 3 webjar is on the classpath, indicating compatibility mode: jar:file:/C:/Users/agoreli/.m2/repository/org/webjars/bowergithub/polymer/polymer/2.7.0/polymer-2.7.0.jar!/META-INF/resources/webjars/polymer/polymer.html. Karibu-Testing 1.2.x doesn't support Vaadin 14 Compatibility mode; please use Karibu-Testing 1.1.x instead
	at com.github.mvysny.kaributesting.v10.VaadinMeta.checkNotVaadin14CompatMode(VaadinVersion.kt:96)
	at com.github.mvysny.kaributesting.v10.VaadinMeta.isCompatibilityMode(VaadinVersion.kt:71)
	at com.github.mvysny.kaributesting.v10.MockVaadin.setup(MockVaadin.kt:148)
	at com.sdn.ui.muse.ui.topology.KaribuVaadin14Spring2Test.setup(KaribuVaadin14Spring2Test.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)

**Comment by mvysny** [comment]
Hi, this is the official Vaadin T-Shirt example which doesn't use Karibu-Testing. Please file a bug against the following repository instead: https://github.com/mvysny/t-shirt-shop-example .

Regarding the issue: please see this issue for more details: https://github.com/mvysny/karibu-testing/issues/56
